# Generated by Django 5.0.2 on 2024-02-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_topic_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us_model',
            name='date',
        ),
    ]
