# Generated by Django 5.0.2 on 2024-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_sharestory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary_Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Diary',
                'ordering': ('-data_created',),
            },
        ),
    ]
